version: 2

jobs:
  pipeline:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm


      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  workflow:
    jobs:
      - pipeline:
          filters:
            branches:
              only:
                - main
                - master
